service: dio-live-project

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: "20201221"
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:GetItem
            - dynamodb:Scan
          Resource:
            - arn:aws:dynamodb:us-east-1:167880115321:table/ToDoTable

functions:
  createTask:
    handler: src/create-task.handler
    events:
      - http:
          path: /task
          method: post
  fetchAllTask:
    handler: src/fetch-all-tasks.handler
    events:
      - http:
          path: /tasks
          method: get
  fechTaskStatus:
    handler: src/fetch-task-by-status.handler
    events:
      - http:
          path: /tasks/{status}
          method: get
  chooseStatus:
    handler: src/choose-status-task.handler
    events:
      - http:
          path: /task/{id}
          method: put
resources:
  Resources:
    ItemTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ToDoTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

plugins:
  # plus to serverless work offile
  - serverless-offline

custom:
  # This is necessary because the docker to use this host
  serverless-offline:
    host: 0.0.0.0            